permalink: pretty
title: Самашрум
description: Самашрум - официальный сайт автора
theme: jekyll-theme-cayman

url: "https://samashroom.ru"
baseurl: ""

social_links: true
author: Самашрум
github_username: Samashroom
youtube_username: Samashroom      # или просто ссылка
telegram_username: Samashroom    # username в телеграме (без @)
tiktok_username: Samashroom 

# Настройки сборки
markdown: kramdown
highlighter: rouge

# Исключаем ненужные файлы из финальной сборки
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .gitignore

plugins:
  - jekyll-seo-tag     
  - jekyll-sitemap      
  - jekyll-feed          
  - jemoji              

lang: ru-RU

collections:
  gallery:           # поменяли с works на gallery
    output: true
    permalink: /gallery/:title/   # и в ссылке тоже gallery

# Настройки по умолчанию для работ
defaults:
  - scope:
      path: ""
      type: gallery   # и здесь поменяли на gallery
    values:
      layout: work_new  
      image_path: 
